timezone: Europe/Rome
permalink: pretty
repository: trasparente/sec6
# remote_theme: trasparente/mdr@gh-pages

# DEFAULTS
# defaults:
#   - scope:
#       path: ''
#     values:
#       layout: default

# COLLECTIONS
# collections:
#   docs:
#     title: Docs
#     output: true
#   posts:
#     title: Posts